name: Test

on: [push, pull_request]

jobs:
  test:
    name: Build and test
    runs-on: Ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
        c-compiler: ['clang', 'gcc']
        cmake-version: ['3.13', 'latest']
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python requirements
      run: |
        pip install -U pip
        pip install -U -r requirements.txt
    - name: Setup CMake ${{ matrix.cmake-version }}
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: ${{ matrix.cmake-version }}
    - name: Configure project
      run: |
        cmake -S. -Bbuild -DCMAKE_WARNINGS_AS_ERRORS=1
      env:
        CC: ${{ matrix.c-compiler }}
    - name: Build library
      run: |
        cmake --build build --parallel
    - name: Build & run tests
      run: |
        cd build
        ctest --output-on-failure --parallel 4
      env:
        CC: ${{ matrix.c-compiler }}
